// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903054638_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Aggregates.MatchAggregate.BattingScore", b =>
                {
                    b.Property<Guid>("InningsId")
                        .HasColumnType("uuid");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Balls")
                        .HasColumnType("integer");

                    b.Property<int>("Fours")
                        .HasColumnType("integer");

                    b.Property<int>("Runs")
                        .HasColumnType("integer");

                    b.Property<int>("Sixes")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Dismissal", "Domain.Aggregates.MatchAggregate.BattingScore.Dismissal#Dismissal", b1 =>
                        {
                            b1.Property<int?>("FielderId")
                                .HasColumnType("integer")
                                .HasColumnName("DismissalFielderId");

                            b1.Property<int>("WicketType")
                                .HasColumnType("integer")
                                .HasColumnName("DismissalWicketType");
                        });

                    b.HasKey("InningsId", "PlayerId");

                    b.ToTable("BattingScores", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.MatchAggregate.BowlingScore", b =>
                {
                    b.Property<Guid>("InningsId")
                        .HasColumnType("uuid");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Balls")
                        .HasColumnType("integer");

                    b.Property<int>("Maidens")
                        .HasColumnType("integer");

                    b.Property<int>("RunsConceded")
                        .HasColumnType("integer");

                    b.Property<int>("TotalWickets")
                        .HasColumnType("integer");

                    b.HasKey("InningsId", "PlayerId");

                    b.ToTable("BowlingScores", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.MatchAggregate.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("BallNumberInOver")
                        .HasColumnType("integer");

                    b.Property<int>("BatterRuns")
                        .HasColumnType("integer");

                    b.Property<int>("BowlerId")
                        .HasColumnType("integer");

                    b.Property<int?>("DismissedPlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("ExtraType")
                        .HasColumnType("integer");

                    b.Property<int>("NonStrikerId")
                        .HasColumnType("integer");

                    b.Property<Guid>("OverId")
                        .HasColumnType("uuid");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<int>("StrikerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalRuns")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Dismissal", "Domain.Aggregates.MatchAggregate.Delivery.Dismissal#Dismissal", b1 =>
                        {
                            b1.Property<int?>("FielderId")
                                .HasColumnType("integer")
                                .HasColumnName("DismissalFielderId");

                            b1.Property<int>("WicketType")
                                .HasColumnType("integer")
                                .HasColumnName("DismissalWicketType");
                        });

                    b.HasKey("Id");

                    b.HasIndex("OverId");

                    b.ToTable("Deliveries", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.MatchAggregate.Innings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("BattingTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("BowlingTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentBowlerId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentNonStrikerId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentStrikerId")
                        .HasColumnType("integer");

                    b.Property<int>("InningsNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxOvers")
                        .HasColumnType("integer");

                    b.Property<int>("SuperOverNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetRuns")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBalls")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRuns")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("Wickets")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "InningsNumber")
                        .IsUnique();

                    b.ToTable("Innings", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.MatchAggregate.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("ActiveScorerId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentSuperOverNumber")
                        .HasColumnType("integer");

                    b.Property<int>("MaxOvers")
                        .HasColumnType("integer");

                    b.Property<int?>("Result")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Team1TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("Team2TeamId")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamBattingFirstId")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamBattingSecondId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TossWonTeamId")
                        .HasColumnType("integer");

                    b.Property<int?>("WinnerTeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id", "Team1TeamId")
                        .IsUnique();

                    b.HasIndex("Id", "Team2TeamId")
                        .IsUnique();

                    b.ToTable("Matches", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.MatchAggregate.Over", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InningsId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("boolean");

                    b.Property<int>("OverNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InningsId", "OverNumber")
                        .IsUnique();

                    b.ToTable("Overs", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.MatchAggregate.PlayingTeam", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("MatchId", "TeamId");

                    b.ToTable("PlayingTeams", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.MatchAggregate.PlayingTeamPlayer", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.HasKey("MatchId", "TeamId", "PlayerId");

                    b.ToTable("PlayingTeamPlayers", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.MatchAggregate.BattingScore", b =>
                {
                    b.HasOne("Domain.Aggregates.MatchAggregate.Innings", null)
                        .WithMany("BattingScores")
                        .HasForeignKey("InningsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.MatchAggregate.BowlingScore", b =>
                {
                    b.HasOne("Domain.Aggregates.MatchAggregate.Innings", null)
                        .WithMany("BowlingScores")
                        .HasForeignKey("InningsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.MatchAggregate.Delivery", b =>
                {
                    b.HasOne("Domain.Aggregates.MatchAggregate.Over", null)
                        .WithMany("Deliveries")
                        .HasForeignKey("OverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.MatchAggregate.Innings", b =>
                {
                    b.HasOne("Domain.Aggregates.MatchAggregate.Match", null)
                        .WithMany("Innings")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.MatchAggregate.Match", b =>
                {
                    b.HasOne("Domain.Aggregates.MatchAggregate.PlayingTeam", "Team1PlayingTeam")
                        .WithOne()
                        .HasForeignKey("Domain.Aggregates.MatchAggregate.Match", "Id", "Team1TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.MatchAggregate.PlayingTeam", "Team2PlayingTeam")
                        .WithOne()
                        .HasForeignKey("Domain.Aggregates.MatchAggregate.Match", "Id", "Team2TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team1PlayingTeam");

                    b.Navigation("Team2PlayingTeam");
                });

            modelBuilder.Entity("Domain.Aggregates.MatchAggregate.Over", b =>
                {
                    b.HasOne("Domain.Aggregates.MatchAggregate.Innings", null)
                        .WithMany("Overs")
                        .HasForeignKey("InningsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.MatchAggregate.PlayingTeamPlayer", b =>
                {
                    b.HasOne("Domain.Aggregates.MatchAggregate.PlayingTeam", null)
                        .WithMany("Players")
                        .HasForeignKey("MatchId", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.MatchAggregate.Innings", b =>
                {
                    b.Navigation("BattingScores");

                    b.Navigation("BowlingScores");

                    b.Navigation("Overs");
                });

            modelBuilder.Entity("Domain.Aggregates.MatchAggregate.Match", b =>
                {
                    b.Navigation("Innings");
                });

            modelBuilder.Entity("Domain.Aggregates.MatchAggregate.Over", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("Domain.Aggregates.MatchAggregate.PlayingTeam", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
